-- MySQL Script generated by MySQL Workbench
-- Tue Aug 22 20:23:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema memes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema memes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `memes` DEFAULT CHARACTER SET utf8 ;
USE `memes` ;

-- -----------------------------------------------------
-- Table `memes`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memes`.`Album` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `nomeAlbum` VARCHAR(45) NOT NULL,
  `ano` YEAR NOT NULL,
  PRIMARY KEY (`idAlbum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memes`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memes`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `nomeGenero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memes`.`Musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memes`.`Musica` (
  `idMusica` INT NOT NULL AUTO_INCREMENT,
  `nomeMusica` VARCHAR(45) NOT NULL,
  `score` FLOAT NOT NULL DEFAULT 0,
  `letra` LONGTEXT NOT NULL,
  `albumMusica` INT NOT NULL,
  `generoMusica` INT NOT NULL,
  PRIMARY KEY (`idMusica`),
  INDEX `fk_Musica_Album1_idx` (`albumMusica` ASC),
  INDEX `fk_Musica_Genero1_idx` (`generoMusica` ASC),
  CONSTRAINT `fk_Musica_Album1`
    FOREIGN KEY (`albumMusica`)
    REFERENCES `memes`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musica_Genero1`
    FOREIGN KEY (`generoMusica`)
    REFERENCES `memes`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memes`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memes`.`Artista` (
  `idArtista` INT NOT NULL AUTO_INCREMENT,
  `nomeArtista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memes`.`Composicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memes`.`Composicao` (
  `Artista_idArtista` INT NOT NULL,
  `Musica_idMusica` INT NOT NULL,
  PRIMARY KEY (`Artista_idArtista`, `Musica_idMusica`),
  INDEX `fk_Artista_has_Musica_Musica1_idx` (`Musica_idMusica` ASC),
  INDEX `fk_Artista_has_Musica_Artista1_idx` (`Artista_idArtista` ASC),
  CONSTRAINT `fk_Artista_has_Musica_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `memes`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artista_has_Musica_Musica1`
    FOREIGN KEY (`Musica_idMusica`)
    REFERENCES `memes`.`Musica` (`idMusica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memes`.`Participa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memes`.`Participa` (
  `Musica_idMusica` INT NOT NULL,
  `Artista_idArtista` INT NOT NULL,
  `papel` INT NOT NULL DEFAULT 1,
  `ordem` INT NOT NULL,
  PRIMARY KEY (`Musica_idMusica`, `Artista_idArtista`),
  INDEX `fk_Musica_has_Artista_Artista1_idx` (`Artista_idArtista` ASC),
  INDEX `fk_Musica_has_Artista_Musica1_idx` (`Musica_idMusica` ASC),
  CONSTRAINT `fk_Musica_has_Artista_Musica1`
    FOREIGN KEY (`Musica_idMusica`)
    REFERENCES `memes`.`Musica` (`idMusica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musica_has_Artista_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `memes`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memes`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memes`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `perfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memes`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memes`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `nota` INT NOT NULL,
  `comentario` VARCHAR(200) NULL,
  `revisao` TINYINT NULL,
  `musicaAvaliacao` INT NOT NULL,
  `usuarioAvaliacao` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `fk_Avaliacao_Musica1_idx` (`musicaAvaliacao` ASC),
  INDEX `fk_Avaliacao_Usuario1_idx` (`usuarioAvaliacao` ASC),
  CONSTRAINT `fk_Avaliacao_Musica1`
    FOREIGN KEY (`musicaAvaliacao`)
    REFERENCES `memes`.`Musica` (`idMusica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Usuario1`
    FOREIGN KEY (`usuarioAvaliacao`)
    REFERENCES `memes`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
